# Generated by Django 4.0.6 on 2022-07-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.IntegerField()),
                ('bookName', models.CharField(max_length=50)),
                ('bookAuthor', models.CharField(max_length=50)),
                ('bookBorrowed', models.CharField(choices=[('BR', 'Borrowed'), ('AV', 'Available')], default='AV', max_length=2)),
                ('bookBorrower', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libId', models.IntegerField()),
                ('libName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberId', models.IntegerField()),
                ('memberName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.IntegerField()),
                ('roleName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberIds', to='libraryapp.member')),
                ('memberRole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MemRoleIds', to='libraryapp.roles')),
            ],
        ),
        migrations.CreateModel(
            name='LibRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='libIds', to='libraryapp.librarian')),
                ('libRole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='libRoleIds', to='libraryapp.roles')),
            ],
        ),
    ]
