# Generated by Django 4.0.6 on 2022-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='libPassword',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='memberPassword',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
